from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol

from agent_fleet.domain.models import (
    AgentInstance,
    ApprovalRequest,
    ArtifactMetadata,
    CapabilityGrant,
    FleetEvent,
    Project,
    ResourceLease,
    Run,
    StoredToolIntent,
    TaskSpec,
    ToolIntent,
)


class StateStore(Protocol):
    def migrate(self) -> int: ...

    def save_project(self, project: Project) -> None: ...

    def get_project(self, project_id: str) -> Project: ...

    def get_project_by_root(self, canonical_root: str) -> Project | None: ...

    def create_run(self, run: Run) -> None: ...

    def get_run(self, run_id: str) -> Run: ...

    def save_run(self, run: Run, event_type: str, payload: dict[str, object]) -> Run: ...

    def save_task(self, task: TaskSpec) -> None: ...

    def get_task(self, task_id: str) -> TaskSpec: ...

    def save_agent_instance(self, instance: AgentInstance) -> None: ...

    def append_event(self, event: FleetEvent) -> FleetEvent: ...

    def list_events(self, run_id: str) -> Sequence[FleetEvent]: ...

    def save_artifact(self, artifact: ArtifactMetadata) -> None: ...

    def get_artifact(self, artifact_id: str) -> ArtifactMetadata: ...

    def list_artifacts(self, run_id: str) -> Sequence[ArtifactMetadata]: ...

    def find_intent(self, run_id: str, idempotency_key: str) -> StoredToolIntent | None: ...

    def reserve_intent(self, intent: ToolIntent, intent_hash: str) -> StoredToolIntent: ...

    def create_approval_and_pause(
        self, intent: ToolIntent, intent_hash: str, request: ApprovalRequest
    ) -> StoredToolIntent: ...

    def get_approval(self, request_id: str) -> ApprovalRequest: ...

    def resolve_approval(
        self, request_id: str, *, approve: bool, denial_reason: str | None
    ) -> CapabilityGrant | None: ...

    def consume_grant_and_reserve(self, request_id: str, intent_hash: str) -> StoredToolIntent: ...

    def complete_intent(self, intent_id: str, result: dict[str, object]) -> StoredToolIntent: ...

    def deny_intent(self, intent_id: str) -> None: ...

    def save_lease(self, lease: ResourceLease) -> None: ...

    def get_lease(self, lease_id: str) -> ResourceLease: ...

    def update_lease_status(self, lease_id: str, status: str) -> None: ...

    def mark_execution_creation_dispatched(self, lease_id: str) -> ResourceLease: ...

    def activate_lease(self, lease_id: str, metadata: dict[str, object]) -> ResourceLease: ...

    def finalize_lease(
        self,
        lease_id: str,
        status: str,
        metadata: dict[str, object],
    ) -> ResourceLease: ...

    def active_leases(self, run_id: str | None = None) -> Sequence[ResourceLease]: ...

    def list_leases(self, run_id: str) -> Sequence[ResourceLease]: ...

    def outstanding_leases(self, run_id: str | None = None) -> Sequence[ResourceLease]: ...

    def count_executed_intents(self, run_id: str, action: str) -> int: ...
